export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_IN_ERROR = 'USER_LOG_IN_ERROR'
export const USER_LOG_IN_ERROR_CLEAR = 'USER_LOG_IN_ERROR_CLEAR'

export const USER_SIGN_UP = 'USER_SIGN_UP'
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR'
export const USER_SIGN_UP_ERROR_CLEAR = 'USER_SIGN_UP_ERROR_CLEAR'

export const USER_LOG_OUT = 'USER_LOG_OUT'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const USER_AUTO_AUTH = 'USER_AUTO_AUTH'
