name: Lint and Build Server

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    name: Lint and Build Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Cache dependencies
        id: cache-node-dep
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-dependencies-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-dep.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build
